#!/bin/sh
set -eu

case "${NEBIUS_SERVERLESS_ENABLED:-false}" in
  true)
    ;;
  false|"")
    export NEBIUS_ENDPOINT_MODE=mock
    export ENDPOINT_TOKEN=
    export NEBIUS_ENDPOINT_BASE_URL=
    export NEBIUS_INCIDENT_EXPLAINER_URL=
    export NEBIUS_SCENARIO_GENERATOR_URL=
    export NEBIUS_MARKET_ABUSE_SCENARIO_URL=
    export NEBIUS_ORDERBOOK_ALERT_URL=
    export NEBIUS_INVESTIGATION_REPORT_URL=
    export NEBIUS_INVESTIGATION_TEAM_URL=
    export NEBIUS_JOB_SUBMIT_COMMAND_TEMPLATE=
    export NEBIUS_JOB_STATUS_COMMAND_TEMPLATE=
    export NEBIUS_JOB_LOGS_COMMAND_TEMPLATE=
    export NEBIUS_JOB_ARTIFACTS_COMMAND_TEMPLATE=
    export NEBIUS_JOB_HEALTH_COMMAND=
    export NEBIUS_OBJECT_STORAGE_ACCESS_KEY_ID=
    export NEBIUS_OBJECT_STORAGE_SECRET_ACCESS_KEY=
    export NEBIUS_OBJECT_STORAGE_SESSION_TOKEN=
    export NEBIUS_EVIDENCE_ARCHIVE_ENABLED=false
    ;;
  *)
    printf '%s\n' "Invalid NEBIUS_SERVERLESS_ENABLED=${NEBIUS_SERVERLESS_ENABLED}; expected true or false" >&2
    exit 2
    ;;
esac

exec "$@"
