apiVersion: v1
kind: Secret
metadata:
  name: aimada-secrets
  namespace: aimada
type: Opaque
stringData:
  ENDPOINT_TOKEN: "replace-me"
  NEBIUS_OBJECT_STORAGE_ACCESS_KEY_ID: ""
  NEBIUS_OBJECT_STORAGE_SECRET_ACCESS_KEY: ""
  NEBIUS_OBJECT_STORAGE_SESSION_TOKEN: ""
